import Amplify from 'aws-amplify';
import React from 'react';
import ReactDOM from 'react-dom';
import { BrowserRouter as Router } from 'react-router-dom';
import App from './App';
import appSyncConfig from './aws-exports.js';
//import Playground from "./Playground";
//import CompanyPage from "./pages/CompanyPage";
import './index.css';
import registerServiceWorker from './registerServiceWorker';

// connects the autogenerated config file for aws resources to Amplify
Amplify.configure(appSyncConfig);

ReactDOM.render(
  // --- PRODUCTION ---
  <Router>
    <App />
  </Router>,

  // --- DEV ---
  // <CompanyPage />,
  // <Playground />,
  document.getElementById('root')
);
registerServiceWorker();
